export const BACKGROUND = 'background'
export const PLATE = 'plate'
export const TOAST_UNLOCKED = 'toastunlocked'
export const TOAST_UNLOCKED_ANIM = 'toastUnlockedAnim'
export const TOAST_EGG = 'toastegg'
export const TOAST_EGG_ANIM = 'toastEggAnim'
export const TOAST_JAM = 'toastjam'
export const TOAST_JAM_ANIM = 'toastJamAnim'
export const ARROW = 'arrow'
export const SPEED_BG = 'speedbg'
export const SPEED_BG_ANIM = 'speedAnim'
export const STRAW = 'straw'
export const COLA = 'cola'

export const LOST_SFX = 'lostSFX'
export const WIN_SFX = 'winSFX'
export const SPLAT_SFX = 'splatSFX'
export const WOOSH_SFX = 'wooshSFX'
export const SLIP_SFX = 'slipSFX'
export const IDLE_BGM = 'idleBGM'
export const SPIN_BGM = 'spinBGM'

export const WIN_1 = 'win1'
export const WIN_2 = 'win2'
export const WIN_3 = 'win3'
export const FAIL_1 = 'fail1'
export const FAIL_2 = 'fail2'
export const SPLAT = 'splat'
export const WTF = 'wtf'

export const SPLASH_SCREEN = 'splashScreen'